# Ejercicios 
## Facultad Regional Villa Maria
### Autor: Santa Coloma, Milagros
### Materia : Inteligencia Artificial 


## Ejericio 2

Construir las matrices

In [19]:
import numpy as np 
from scipy.linalg import *
A = np.array([[1,2,3],
            [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
B=np.array([[-1,0],
            [1,1],
            [0,1]])
B

array([[-1,  0],
       [ 1,  1],
       [ 0,  1]])

Hacer con dicas Matrices $A-B^T$ e imprimir su resultado

In [21]:
b=B.transpose()
b

array([[-1,  1,  0],
       [ 0,  1,  1]])

In [22]:
resta=A.__sub__(b)
resta

array([[2, 1, 3],
       [4, 4, 5]])

Hacer con dicas matrices $(A.B)^{-1}$ e imprimir su resultado.

In [23]:
mul=np.dot(A,B)
mul

array([[ 1,  5],
       [ 1, 11]])

In [24]:
c=inv(mul)
c

array([[ 1.83333333, -0.83333333],
       [-0.16666667,  0.16666667]])